version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eldorado-server
    environment:
      - PORT=1234
      - NODE_ENV=development
    ports:
      - '1234:1234'
    command: yarn start
